name = "filthy_purple_bandicoot-78cd"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "filthy_purple_bandicoot-78cd_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "filthy_purple_bandicoot-78cd.wasm"
command = "npm run build:release"
